# This is a basic workflow to help you get started with Actions

name: DEV CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm run test-cypress
          wait-on: "http://localhost:8080"
          browser: chrome
          headless: true

